### ISSUE TITLE
Export `errClosedListener`

### ISSUE THREAD

**Issue by besedad** [pion/udp#37]
## Summary

Export `errClosedListener` as `ErrClosedListener` so that the error can be handled explicitly outside of the package.

## Motivation

The only way to gracefully shutdown a listener is by calling `Close`. Under such circumstances, `errClosedListener` returned by `Accept` isn't an error that requires user's attention, and as such, can be ignored (e.g. hidden in log output).

## Describe alternatives you've considered

The only alternative is matching the error string:

```golang
conn, err := listener.Accept()
if err != nil {
    if err.Error() == "udp: listener closed" {
        return nil
    }
    fmt.Println("accept error: %v", err)
    return err
}
```

**Comment by Sean-Der** [comment]
Yes please export! Happy to accept that PR right away

**Comment by Sean-Der** [comment]
Merged with https://github.com/pion/udp/commit/534f92eb13db661274eb15a8ea186585e9f1e182
