### ISSUE TITLE
Merge into github.com/pion/transport

### ISSUE THREAD

**Issue by stv0g** [pion/udp#91]
Can we merge this repo into the github.com/pion/transport package?

I dont see a reason why this code needs to live in a separate repo.

**Comment by Sean-Der** [comment]
👍 from me!

We can deprecate this package and then update all current users to use github.com/pion/transport

**Comment by stv0g** [comment]
I created a PR in github.com/pion/transport: https://github.com/pion/transport/pull/234

@Sean-Der Do you mind approving it? I would archive this repo afterwards.
